<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>60</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8f066d38-8fb4-4de0-870b-273d0097e2dc</testSuiteGuid>
   <testCaseLink>
      <guid>9c5b330c-c26c-4267-a288-7a83785b8d52</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Manual/Login/Login with valid credential with variable</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>900d92b5-552c-4814-8479-ea79c202a79f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>900d92b5-552c-4814-8479-ea79c202a79f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>d58fc4b9-561c-4126-b9b8-7eb33805dedd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>900d92b5-552c-4814-8479-ea79c202a79f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>4564e92a-5ab2-4303-9037-9777b7952408</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
